TARGET = flyby2.exg
OBJ = flyby.obj asmoke.obj





DOSEXT = run386
BINPATH = c:/hc386/bin
LIBPATH = c:/hc386/small

USERLIBDIR=../lib
USERINCDIR=../include


CC = $(DOSEXT) HCD386P
LINK = $(DOSEXT) TLINKP -STACK 98000
CFLAGS =
LNKFILE=towns.lnk




$(TARGET) : $(OBJ)
		$(LINK) @$(LNKFILE)



.c.obj:
	$(CC) $(CFLAGS) $*.c
