TARGET=libimpulse.a
INCLUDE=../impulse.h

CC = gcc
CFLAGS =
#if error occured in Solaris
#CFLAGS = -I/usr/local/X11R6/include


.IGNORE:





OBJ = ixwin.o \
      i2dg.o \
      i2dpict.o \
      i3dg.o \
      i3dgbbox.o \
      i3dgobj.o \
      ibmpfile.o \
      icalc.o \
      icalctab.o \
      iclock.o \
      idevice.o \
      iepsfile.o \
      iepslink.o \
      ifield.o \
      ilncross.o \
      imodel.o \
      iprimrc.o \
      irender.o \
      irendlnk.o \
      irendplg.o \
      irendtri.o \
      iscrn.o \
      iterrain.o \
      itiffile.o \
      itmpheap.o \
      itwist.o \
      iutil.o \
      i3dtext.o \
      ippmfile.o \
      istrrc.o \
      ivrmfile.o \
      iclick.o \
      ipolyg.o




$(TARGET) : $(OBJ)
	ar cru $(TARGET) $(OBJ)
	ranlib $(TARGET)



i2dg.o : ../i2dg.c
	$(CC) -c ../i2dg.c $(CFLAGS)

i2dpict.o : ../i2dpict.c
	$(CC) -c ../i2dpict.c $(CFLAGS)

i3dg.o : ../i3dg.c
	$(CC) -c ../i3dg.c $(CFLAGS)

i3dgbbox.o : ../i3dgbbox.c
	$(CC) -c ../i3dgbbox.c $(CFLAGS)

i3dgobj.o : ../i3dgobj.c
	$(CC) -c ../i3dgobj.c $(CFLAGS)

ibmpfile.o : ../ibmpfile.c
	$(CC) -c ../ibmpfile.c $(CFLAGS)

icalc.o : ../icalc.c
	$(CC) -c ../icalc.c $(CFLAGS)

icalctab.o : ../icalctab.c
	$(CC) -c ../icalctab.c $(CFLAGS)

iclock.o : ../iclock.c
	$(CC) -c ../iclock.c $(CFLAGS)

idevice.o : ../idevice.c
	$(CC) -c ../idevice.c $(CFLAGS)

iepsfile.o : ../iepsfile.c
	$(CC) -c ../iepsfile.c $(CFLAGS)

iepslink.o : ../iepslink.c
	$(CC) -c ../iepslink.c $(CFLAGS)

ifield.o : ../ifield.c
	$(CC) -c ../ifield.c $(CFLAGS)

ilncross.o : ../ilncross.c
	$(CC) -c ../ilncross.c $(CFLAGS)

imodel.o : ../imodel.c
	$(CC) -c ../imodel.c $(CFLAGS)

iprimrc.o : ../iprimrc.c
	$(CC) -c ../iprimrc.c $(CFLAGS)

irender.o : ../irender.c
	$(CC) -c ../irender.c $(CFLAGS)

irendlnk.o : ../irendlnk.c
	$(CC) -c ../irendlnk.c $(CFLAGS)

irendplg.o : ../irendplg.c
	$(CC) -c ../irendplg.c $(CFLAGS)

irendtri.o : ../irendtri.c
	$(CC) -c ../irendtri.c $(CFLAGS)

iscrn.o : ../iscrn.c
	$(CC) -c ../iscrn.c $(CFLAGS)

iterrain.o : ../iterrain.c
	$(CC) -c ../iterrain.c $(CFLAGS)

itiffile.o : ../itiffile.c
	$(CC) -c ../itiffile.c $(CFLAGS)

itmpheap.o : ../itmpheap.c
	$(CC) -c ../itmpheap.c $(CFLAGS)

itwist.o : ../itwist.c
	$(CC) -c ../itwist.c $(CFLAGS)

iutil.o : ../iutil.c
	$(CC) -c ../iutil.c $(CFLAGS)

i3dtext.o : ../i3dtext.c
	$(CC) -c ../i3dtext.c $(CFLAGS)

istrrc.o : ../istrrc.c
	$(CC) -c ../istrrc.c $(CFLAGS)

ippmfile.o : ../ippmfile.c
	$(CC) -c ../ippmfile.c $(CFLAGS)

ivrmfile.o : ../ivrmfile.c
	$(CC) -c ../ivrmfile.c $(CFLAGS)

iclick.o : ../iclick.c
	$(CC) -c ../iclick.c $(CFLAGS)

ipolyg.o : ../ipolyg.c
	$(CC) -c ../ipolyg.c $(CFLAGS)




ixwin.o : ixwin.c
	$(CC) -c ixwin.c $(CFLAGS)

