TARGET=libskyhawk.a
INCLUDE=skyhawk.h
OBJ=args.o exprintf.o filename.o reldir.o string.o

CC=gcc
CFLAGS=




.IGNORE:



$(TARGET) : $(OBJ)
	ar cru $(TARGET) $(OBJ)
	ranlib $(TARGET)

.c.o :
	$(CC) -c $*.c $(CFLAGS)
