CC = 386 -c HCD386P
LIB = 386lib
LIBFILE = libfile.lib
CFLAGS =

TARGET = skyhawk.lib
HEADER = skyhawk.h
USERINCDIR = E:\hc386\inc
USERLIBDIR = E:\hc386\small

OBJ = args.obj exprintf.obj filename.obj reldir.obj string.obj


$(TARGET) : $(OBJ)
	del $(TARGET)
	$(LIB) @<<$(LIBFILE)
		$(TARGET) -create $(OBJ)
<<
	cp $(TARGET) $(USERLIBDIR)
	cp $(HEADER) $(USERINCDIR)

.c.obj :
	$(CC) $*.c $(CFLAGS)

