CC = run386 HCD386P
LIB = 386lib
LIBFILE = lib.lbc
CFLAGS =

TARGET = skyhawk.lib
HEADER = skyhawk.h
USERINCDIR = ..\..\include
USERLIBDIR = ..\..\lib

OBJ = args.obj exprintf.obj filename.obj reldir.obj string.obj


$(TARGET) : $(OBJ)
	del $(TARGET)
	$(LIB) @$(LIBFILE)
	copy $(TARGET) $(USERLIBDIR)
	copy $(HEADER) $(USERINCDIR)

.c.obj :
	$(CC) $*.c $(CFLAGS)

