CC = 386 -c HCD386P
LIB = 386lib
LIBFILE = libfile.lib
CFLAGS =

TARGET = AURORA.LIB
HEADER = aurora.h
USERINCDIR = E:\hc386\inc
USERLIBDIR = E:\hc386\small

OBJ = adyna.obj \
      adynaf.obj \
      aurora.obj \
      asmoke.obj \
      apath.obj \
      apathf.obj \
      afldfile.obj \
      ashare.obj



$(TARGET) : $(OBJ)
	del $(TARGET)
	$(LIB) @<<$(LIBFILE)
		$(TARGET) -create $(OBJ)
<<
	cp $(TARGET) $(USERLIBDIR)
	cp $(HEADER) $(USERINCDIR)



.c.obj :
	$(CC) $(CFLAGS) $*.c
